version: "3"
services:
  gateway:
    image: krakend/krakend-ee:2.5.3
    environment:
      - FC_CONFIG=/etc/krakend/flexible_config.json
    volumes:
      - ./gateway/config:/etc/krakend
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
      - "15000:15000"
    command:
      [
        sh,
        -c,
        "krakend run -d -c /etc/krakend/krakend.tmpl",
      ]
    depends_on:
      - greeter
  greeter:
    image: greeter:latest
    ports:
      - "50051:50051"
