version: "3"
services:
  gateway:
    image: krakend/krakend-ee:alpha-33905b2
    environment:
      - FC_ENABLE=1
      - FC_TEMPLATES=/etc/krakend/templates
    volumes:
      - ./gateway/config:/etc/krakend
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    command: ["run", "-d", "-c", "krakend.tmpl"]
    depends_on:
      - greeter
  greeter:
    image: greeter:latest
    ports:
      - "50051:50051"
